name: CI para C

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o reposit√≥rio
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      uses: sudo apt update && sudo apt install build-essential -y

    - name: Compilar programa
      uses: gcc github.c -o programa

    - name: Executar o programa
      uses: ./programa

    - name: Executar testes automatizados
      run: |
        gcc -o teste teste.c
        ./teste
